language: c
os:
  - linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - autoconf
      - automake
      - autopoint
      - make
      - gcc
      - debhelper
      - devscripts
      - libtool
      - build-essential
      - pkg-config
      - libtalloc-dev
      - libpcsclite-dev
      - libpcap-dev
      - libzmq3-dev
      - libgnutls28-dev

script:
  - contrib/travis.sh
